name: circuit_electricial_box
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ming_cute_icons: ^0.0.6
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  go_router: ^14.6.0
  get_it: ^8.0.2
  firebase_core: ^3.4.0
  dots_indicator: ^3.0.0
  flutter_native_splash: ^2.4.2
  equatable: ^2.0.5
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.14
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.8.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/circuit/
  - assets/images/
  - assets/icon/
  fonts:
  - family: Quicksand
    fonts:
      - asset: assets/fonts/Quicksand-Light.ttf
        weight: 300
      - asset: assets/fonts/Quicksand-Regular.ttf
        weight: 400
      - asset: assets/fonts/Quicksand-Medium.ttf
        weight: 500
      - asset: assets/fonts/Quicksand-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Quicksand-Bold.ttf
        weight: 700

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arb_file: intl_en.arb
  output-dir: lib/generated
